### ISSUE TITLE
Show all ads screen: Why 1 ad is displayed 4 times ? screenshot attached!

### ISSUE THREAD

**Issue by maryam-awan** [sofittech/celx-web-project#10]
![Screenshot 2020-03-17 at 12 03 00 PM](https://user-images.githubusercontent.com/40426826/76830642-7e59c300-6847-11ea-867d-5c01ae4d16e3.png)

**Comment by shafiq-techmentors** [comment]
Fixed the issue. it was because the component structure was wrong and the rows were repeating along with single item

**Comment by isabeen** [comment]
@shafiq-techmentors you are not supposed to close the issues.
