### ISSUE TITLE
Single Ad detail screen: Why the design looks like this ? also please minimize the width as i told earlier. Screenshot attached!

### ISSUE THREAD

**Issue by maryam-awan** [sofittech/celx-web-project#11]
![Screenshot 2020-03-17 at 12 03 21 PM](https://user-images.githubusercontent.com/40426826/76830745-bd881400-6847-11ea-8398-027f9020143f.png)

**Comment by shafiq-techmentors** [comment]
I have not worked on the design of this component and also I have shown the data from the API in my extra time. I am going to fix the design but it will take some time. Let me confirm on time whether I go for it OR do something else on priority base.

**Comment by isabeen** [comment]
@shafiq-techmentors @maryam-awan  This issue could not be closed as dummy texts and pictures are added in the ad detail screen which are not actually present there. 
![ssss](https://user-images.githubusercontent.com/53593496/76946179-740df680-6925-11ea-97b2-cf7f4883e094.jpg)

**Comment by isabeen** [comment]
@shafiq-techmentors please follow the design

**Comment by shafiq-techmentors** [comment]
The dummy text is removed, the currency is coming along with me when you first land on the page, the location is coming from the API and there is "Not Available" in API for this ad. The pictures are also coming from the API. so contact API dev.

**Comment by isabeen** [comment]
@shafiq-techmentors you need to follow the design.
