### ISSUE TITLE
Currency is missing on Ads. it must be shown with the price.

### ISSUE THREAD

**Issue by maryam-awan** [sofittech/celx-web-project#12]

**Comment by shafiq-techmentors** [comment]
Currency is showing along with the ads Now. If still, you can't see please drop me a screenshot.

**Comment by isabeen** [comment]
@shafiq-techmentors still no currency is shown. 
![dddd](https://user-images.githubusercontent.com/53593496/76945277-1c22c000-6924-11ea-814d-b716a1914f2a.JPG)

**Comment by shafiq-techmentors** [comment]
<img width="1440" alt="Screenshot 2020-03-25 at 1 09 21 PM" src="https://user-images.githubusercontent.com/44589622/77515260-066c4800-6e9a-11ea-9b16-ef107cf6c1c1.png">

This is what on my side. I don't know why you can't see currency.

**Comment by isabeen** [comment]
Currency is not showing at my side.

@sheerazanwar @shafiq-techmentors please find a way around.

**Comment by shafiq-techmentors** [comment]
oh that's bad. it's showing on my side.so what I can do about that. i think you have a problem with the API urls and haseem and aqib know this well.
