### ISSUE TITLE
View All Results Page: Ad cards are overlapping.  (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#17]
![ggg](https://user-images.githubusercontent.com/53593496/76944899-9acb2d80-6923-11ea-8813-fba7cd1487fc.JPG)

**Comment by shafiq-techmentors** [comment]
<img width="1440" alt="Screenshot 2020-03-25 at 1 13 12 PM" src="https://user-images.githubusercontent.com/44589622/77515575-91e5d900-6e9a-11ea-9335-b419b326a555.png">

No cards are overlapping on my side. Kindly check double check it.
