### ISSUE TITLE
Landing Page: Size of profile picture needs to be reduced a little

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#25]
![jj](https://user-images.githubusercontent.com/53593496/78016989-07ebb380-7365-11ea-8609-73b6c3440bf4.JPG)

**Comment by shafiq-techmentors** [comment]
check it on celx-dev. it's good on my side.

**Comment by isabeen** [comment]
@shafiq-techmentors @HaseemUlHaq please look into this.
Issue exists. Testing done on http://celx-web.herokuapp.com
