### ISSUE TITLE
Offers Information: Minor changes (See screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#27]
![ssssss](https://user-images.githubusercontent.com/53593496/78020680-5603b580-736b-11ea-827f-a981f4ac64f4.JPG)

**Comment by isabeen** [comment]
@shafiq-techmentors this is what I see when I open offers information

![Screenshot (251)](https://user-images.githubusercontent.com/53593496/79544255-29a8a280-80a8-11ea-82be-4f8ae0d5a673.png)

**Comment by shafiq-techmentors** [comment]
<img width="1440" alt="Screenshot 2020-04-22 at 4 57 49 PM" src="https://user-images.githubusercontent.com/44589622/80033311-eb770d00-8505-11ea-9baf-743d11f7f479.png">

The view is changed by Aqib. The rest of the issues fixed with this screen.
