### ISSUE TITLE
Unable to view ads:  Crash due to property null error (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#42]
![Screenshot (273)](https://user-images.githubusercontent.com/53593496/80086122-b05ef300-8572-11ea-8a58-c4144d793c37.png)

**Comment by shafiq-techmentors** [comment]
it's fine on my side now. sometimes when the app crashes then it happens and it's a back-end issue, 

1) Make sure you have dev environment (if you are on rel environment then it happens).
2) The app is not crashed. (you can ask from Maryam to check it the app is not crashed)

**Comment by isabeen** [comment]
@shafiq-techmentors @HaseemUlHaq please look into this.
Issue exists. Testing done on http://celx-web.herokuapp.com

**Comment by isabeen** [comment]
Issue still exists. 
![Uploading 82235235...]()
