### ISSUE TITLE
Landing Page > View All Results: Same ads are repeating throughout the whole row.

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#5]
![aa](https://user-images.githubusercontent.com/53593496/76826765-1f904b80-683f-11ea-8f12-c83faba548de.JPG)

**Comment by shafiq-techmentors** [comment]
Fixed.

**Comment by isabeen** [comment]
@shafiq-techmentors please move the issues to "ready for testing".
Only QA/PM may close the issues.
