### ISSUE TITLE
Landing Page: Scroll bar should not be shown along with filters drop down (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#6]
![vcbv](https://user-images.githubusercontent.com/53593496/76826916-74cc5d00-683f-11ea-9b77-c274e8917596.JPG)

**Comment by shafiq-techmentors** [comment]
This is what I have discussed with @Aqib ad @HaseemUlHaq about multi-selection and searching within it. We were unable to do searching in material UI and tried a lot so I am directed to do something different and then I used the react-select package. Now I have also found solution on material UI too if you say i can go for the solution but will take some time on that too as I have to revert and change many things along.

**Comment by isabeen** [comment]
@shafiq-techmentors I've tagged the issue as Low priority. Lets first resolve the functionality issues.
