### ISSUE TITLE
Filtered Search: Location Pakistan, Model Apple (All Models): Search result issues. (see details)

### ISSUE THREAD

**Issue by isabeen** [sofittech/celx-web-project#7]
In the app there are only 4 ads for this filter search but the landing says '21 Results'.

On selecting 'View All Results', the header says "140 Results" 

The ads shown are not the ones which are shown in the mobile apps.
![z](https://user-images.githubusercontent.com/53593496/76827457-a8f44d80-6840-11ea-8351-932294129595.JPG)

![bbb](https://user-images.githubusercontent.com/53593496/76827523-d2ad7480-6840-11ea-8531-4f51d6eed948.JPG)

**Comment by shafiq-techmentors** [comment]
I have fixed the issue, now showing 4 results and on clicking show all it shows as many adds remaining except the first 4. I have fixed the design of view all components previous days but it becomes the same as the old one. will fix that too. Quick check and let me.

**Comment by shafiq-techmentors** [comment]
Also now showing the same 4 phones as like in Mobile App.

**Comment by isabeen** [comment]
@shafiq-techmentors  it is showing me 37 ads instead of 4 with the selected filters. Maybe there is location issue due to which it is showing more ads.

**Comment by shafiq-techmentors** [comment]
This issue is fixed. and there are two urls, one is with the dev and the one is with the rel, it's working fine with the cerl. so ask aqib to change url to rel. 

this is API call and it's perfect on my side

**Comment by isabeen** [comment]
@sheerazanwar @shafiq-techmentors  Please look into this issue to find a way around.

**Comment by shafiq-techmentors** [comment]
<img width="1440" alt="Screenshot 2020-03-25 at 4 53 05 PM" src="https://user-images.githubusercontent.com/44589622/77533848-6f16ed00-6eb9-11ea-8f1c-04b2096b7137.png">

it's perfect on my side.

**Comment by isabeen** [comment]
@shafiq-techmentors please check the same scenario when the user is not logged in.

**Comment by shafiq-techmentors** [comment]
<img width="1440" alt="Screenshot 2020-03-25 at 5 01 17 PM" src="https://user-images.githubusercontent.com/44589622/77534403-62df5f80-6eba-11ea-92e7-54349dc713ec.png">

please check, now the user is not loggedin
